### ISSUE TITLE
[Wii] Doesn't load, freezes on a black screen

### ISSUE THREAD

**Issue by Cee123** [libretro/vice-libretro#373]
The core will not even load into memory - upon loading the core, it just freezes on a black screen.

**Comment by sonninnos** [comment]
Is this still the case?

**Comment by Cee123** [comment]
> 
> 
> Is this still the case?

As far as I can tell, yeah it's still the same.

**Comment by Cee123** [comment]
> 
> 
> Is this still the case?

I don't know, I haven't looked at this for a while. I'll test it out and see if it still has issues.

**Comment by Cee123** [comment]
> 
> 
> Is this still the case?

I just tried this and as of 27/09/21 with the latest nightly, it's exactly the same. Nothing's changed here. Still black screen, doesn't work.

**Comment by vonmillhausen** [comment]
Still the case with the 1.15 release, sadly :(

**Comment by sonninnos** [comment]
Without logs it is impossible to start guessing what the reason might be.

**Comment by vonmillhausen** [comment]
> Without logs it is impossible to start guessing what the reason might be.

For what it's worth, here's the log (this is full Debug logging turned on in the menu) - as you can see, there's not a lot. As soon as you choose to load the Vice cores, the console locks up with a black screen, and must be force-powered-off.

[retroarch__2023_06_13__00_05_57.log](https://github.com/libretro/vice-libretro/files/11728961/retroarch__2023_06_13__00_05_57.log)

Perhaps the fact that (given the lack of logging) it appears the core locks the console very early in the loading process is itself a clue? I hope it helps! Let me know if there's anything else I can do to help here - if you want to build a core version with even more logging turned on or something, I'm more than happy to do tests on real hardware for anyone on the dev team 👍

**Comment by sonninnos** [comment]
Unfortunately indeed not helpful since there is no "good part" in the log, and no mention of even starting the core at all.. Buildbot build logs look clean also, so not much to go on.

**Comment by vonmillhausen** [comment]
> Unfortunately indeed not helpful since there is no "good part" in the log, and no mention of even starting the core at all.. Buildbot build logs look clean also, so not much to go on.

Aye, which as I say must mean the core is failing to load very early in the load process.

Hypothetically speaking, if it *was* loading successfully, what's the first debug level log entry you would expect to see? If that log entry (whatever it is) isn't being generated, then that must mean the core is failing *before* that point. *What* does the core do before that point? Something in there is the culprit.

As I say, I'm more than happy to do any testing you want to get this old (2+ years) issue closed out, and get this core working again. Would it be possible to make a debug build of the core that has additional logging for every step early in the load process? If you can get a build to me that is as verbose as possible in terms of logging, I can get you a log that's useful.

**Comment by vailkyte** [comment]
I loaded a small core like Handy (2.94 MB) and it launches the menu okay. This is before you even press "Load Core" button.

Vice is 5.99 MB - is it breaking some memory limit in Retroarch itself?

**Comment by vailkyte** [comment]
Does anyone know roughly when the Wii was last working? @Cee123?

I tried this old commit from Oct. 2018 and it still black screens before the menu.
https://github.com/libretro/vice-libretro/commit/d6112d6542ab2a7c4fd40e958cf8c75d726d16a0

I can't find a working devkit to build older Wii RA frontends.

**Comment by vailkyte** [comment]
Tried building all commits, even first one. None seem to load into memory. Unsure it ever worked as no one mentions it in forums.

Frodo was ported to Wii and mentions that 2020 Vice failed.
https://www.lemon64.com/forum/viewtopic.php?t=76082

PSP Vice looks custom built.
https://github.com/rsn8887/pspvice


Only when I strip out nearly everything from libretro-core.c does it try to boot. Maybe the Wii doesn't have enough memory?

This is a Github Actions build script if someone else wants to tinker.
```
on:
  push:
  workflow_dispatch:


jobs:

  build-libretro:
    strategy:
      matrix:
        arch: [wii]
        core: [64]
      fail-fast: false


    runs-on: ubuntu-latest

    steps:

    - shell: bash
      run: |
        git clone https://github.com/libretro/vice-libretro core
        cd core


        # devkitppc r29, 2018-05-22
        docker run --rm -v "$PWD:/build" devkitpro/devkitppc:20180522 sh -c "cd /build; make -f Makefile -j`nproc` platform=wii"


    - shell: bash
      run: |
        git clone https://github.com/libretro/RetroArch.git retroarch
        cd retroarch

        docker run --rm -v "$PWD:/build" --network=host devkitpro/devkitppc:20180522 sh -c "cd /build; make -f Makefile.wii.salamander"

        mv ../core/vice_x64_libretro_wii.a libretro_wii.a
        docker run --rm -v "$PWD:/build" --network=host devkitpro/devkitppc:20180522 sh -c "cd /build; make -f Makefile.griffin platform=wii"


    - uses: actions/upload-artifact@main
      with:
        name: vice_${{ matrix.core }}_${{ matrix.arch }}
        path: ${{ github.workspace }}/retroarch/**.dol
```
